-- =========================================================================
-- Schema de Base de Datos para Supabase — Bar Luna Llena 16
-- =========================================================================

-- 1. Tabla de Información del Negocio (Dirección, Teléfono, Horarios, Redes)
CREATE TABLE IF NOT EXISTS public.business_info (
    id text PRIMARY KEY DEFAULT 'main',
    name text NOT NULL DEFAULT 'Bar Luna Llena 16',
    address text DEFAULT 'Carrer de Cotoner, 16',
    locality text DEFAULT 'Palma de Mallorca',
    postal_code text DEFAULT '07013',
    region text DEFAULT 'Illes Balears',
    telephone text DEFAULT '+34631122757',
    whatsapp text DEFAULT '34631122757',
    email text DEFAULT 'barlunallena16@gmail.com',
    hours_weekdays_es text DEFAULT '08:00h - 23:00h',
    hours_sunday_es text DEFAULT 'Cerrado',
    hours_weekdays_en text DEFAULT '08:00h - 23:00h',
    hours_sunday_en text DEFAULT 'Closed',
    google_maps_url text DEFAULT 'https://maps.app.goo.gl/Wvg1TphkJxpHRdtUA',
    instagram_url text DEFAULT 'https://www.instagram.com/barlunallena',
    is_open boolean DEFAULT true,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.business_info ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir lectura publica de business_info" ON public.business_info;
    CREATE POLICY "Permitir lectura publica de business_info" ON public.business_info FOR SELECT USING (true);
END $$;

-- 2. Tabla de Consentimientos de Cookies (RGPD Compliance)
CREATE TABLE IF NOT EXISTS public.cookie_consents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    visitor_uuid text NOT NULL,
    accepted_essential boolean DEFAULT true,
    accepted_analytics boolean DEFAULT false,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.cookie_consents ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir insercion anonima de cookies" ON public.cookie_consents;
    CREATE POLICY "Permitir insercion anonima de cookies" ON public.cookie_consents FOR INSERT WITH CHECK (true);
END $$;

-- 3. Tabla de Contenidos del Sitio (Traducciones y Textos Editables)
CREATE TABLE IF NOT EXISTS public.site_content (
    key text PRIMARY KEY,
    value_es text NOT NULL,
    value_en text NOT NULL,
    category text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir lectura publica de contenidos" ON public.site_content;
    CREATE POLICY "Permitir lectura publica de contenidos" ON public.site_content FOR SELECT USING (true);
END $$;

-- 4. Tabla de Platos Destacados (Carta Digital)
CREATE TABLE IF NOT EXISTS public.dishes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text UNIQUE NOT NULL,
    title_es text NOT NULL,
    title_en text NOT NULL,
    description_es text NOT NULL,
    description_en text NOT NULL,
    image_url text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.dishes ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir lectura publica de platos" ON public.dishes;
    CREATE POLICY "Permitir lectura publica de platos" ON public.dishes FOR SELECT USING (true);
END $$;

-- 5. Tabla de Reservas de Mesa (Histórico & Backup)
CREATE TABLE IF NOT EXISTS public.reservations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    phone text NOT NULL,
    guests integer NOT NULL DEFAULT 2,
    reservation_date date NOT NULL,
    reservation_time text NOT NULL,
    allergies text,
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir insercion publica de reservas" ON public.reservations;
    CREATE POLICY "Permitir insercion publica de reservas" ON public.reservations FOR INSERT WITH CHECK (true);
END $$;

-- 6. Tabla de Pedidos Rápidos (Histórico & Backup)
CREATE TABLE IF NOT EXISTS public.orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    surname text,
    phone text NOT NULL,
    categories text[],
    notes text,
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    DROP POLICY IF EXISTS "Permitir insercion publica de pedidos" ON public.orders;
    CREATE POLICY "Permitir insercion publica de pedidos" ON public.orders FOR INSERT WITH CHECK (true);
END $$;

-- =========================================================================
-- Datos de Semilla (Seed Data)
-- =========================================================================

-- Información del Local
INSERT INTO public.business_info (id, name, address, locality, postal_code, region, telephone, whatsapp, email, hours_weekdays_es, hours_sunday_es, hours_weekdays_en, hours_sunday_en, google_maps_url, instagram_url, is_open)
VALUES (
    'main',
    'Bar Luna Llena 16',
    'Carrer de Cotoner, 16',
    'Palma de Mallorca',
    '07013',
    'Illes Balears',
    '+34631122757',
    '34631122757',
    'barlunallena16@gmail.com',
    '08:00h - 23:00h',
    'Cerrado',
    '08:00h - 23:00h',
    'Closed',
    'https://maps.app.goo.gl/Wvg1TphkJxpHRdtUA',
    'https://www.instagram.com/barlunallena',
    true
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    telephone = EXCLUDED.telephone,
    whatsapp = EXCLUDED.whatsapp,
    email = EXCLUDED.email,
    updated_at = timezone('utc'::text, now());

-- Contenidos del Sitio
INSERT INTO public.site_content (key, value_es, value_en, category) VALUES
('nav_inicio', 'Inicio', 'Home', 'navigation'),
('nav_historia', 'Historia', 'Our Story', 'navigation'),
('nav_carta', 'Carta', 'Menu', 'navigation'),
('nav_ubicacion', 'Ubicación', 'Location', 'navigation'),
('btn_reservar', 'Reservar', 'Book a Table', 'navigation'),
('hero_eyebrow', 'EST. 2015 &nbsp;·&nbsp; SANTA CATALINA, PALMA', 'EST. 2015 &nbsp;·&nbsp; SANTA CATALINA, PALMA', 'hero'),
('hero_tagline_mobile', '"Tradición, calidad y un ambiente único en el corazón de Santa Catalina."', '"Tradition, quality and a unique atmosphere in the heart of Santa Catalina."', 'hero'),
('hero_tagline_desktop', 'Tradición, calidad y un ambiente nocturno y sofisticado en el corazón de Santa Catalina.', 'Tradition, quality and a unique atmosphere in the heart of Santa Catalina.', 'hero'),
('hero_btn', 'DESCUBRIR LA CARTA DIGITAL', 'DISCOVER DIGITAL MENU', 'hero'),
('story_eyebrow', 'Sobre Nosotros', 'About Us', 'story'),
('story_title', 'Nuestra Historia', 'Our Story', 'story'),
('story_quote', 'En el corazón de Santa Catalina, Bar Luna Llena lleva más de una década siendo un punto de encuentro para vecinos, visitantes y amantes de la buena gastronomía.', 'In the heart of Santa Catalina, Bar Luna Llena has been a meeting point for locals, visitors and lovers of great gastronomy for over a decade.', 'story'),
('story_p1', 'Nuestra esencia siempre ha sido la misma: ofrecer un ambiente cercano, buena comida y un lugar donde disfrutar sin prisas.', 'Our essence has always been the same: to offer a warm atmosphere, great food and a place to enjoy without haste.', 'story'),
('story_p2', 'Y si hay un rincón especial, es nuestra terraza. Un espacio al aire libre donde empezar el día con un café, compartir unas tapas o disfrutar de una cena mientras se vive el ambiente único de Santa Catalina.', 'And if there is a special corner, it is our terrace. An outdoor space to start the day with a coffee, share some tapas or enjoy a dinner while experiencing the unique atmosphere of Santa Catalina.', 'story'),
('story_p3', 'Más que un restaurante, queremos ser ese lugar al que siempre apetece volver.', 'More than a restaurant, we want to be that place you always want to return to.', 'story'),
('story_icon_coffee', 'Café', 'Coffee', 'story'),
('story_icon_tapas', 'Tapas', 'Tapas', 'story'),
('story_icon_terrace', 'Terraza', 'Terrace', 'story'),
('menu_eyebrow', 'Gastronomía', 'Gastronomy', 'menu'),
('menu_title', 'Carta Digital', 'Digital Menu', 'menu'),
('menu_subtitle', 'Destacados para Picar', 'Featured to Share', 'menu'),
('menu_pdf_btn', 'VER CARTA COMPLETA', 'VIEW FULL MENU', 'menu'),
('contact_eyebrow', 'Visítanos', 'Visit Us', 'contact'),
('contact_title', 'Localización & Contacto', 'Location & Contact', 'contact'),
('contact_address_title', 'Dirección', 'Address', 'contact'),
('contact_hours_title', 'Horario', 'Opening Hours', 'contact'),
('contact_hours_value', '<span class="text-white/90">Lunes a Sábado:</span> 08:00h - 23:00h<br/><span class="text-white/90">Domingo:</span> Cerrado', '<span class="text-white/90">Monday to Saturday:</span> 08:00h - 23:00h<br/><span class="text-white/90">Sunday:</span> Closed', 'contact'),
('contact_phone_title', 'Teléfono', 'Phone', 'contact'),
('contact_reviews_btn', 'Leer + Reseñas en Google', 'Read Google Reviews', 'contact'),
('footer_slogan', 'El bar del barrio', 'The neighborhood bar', 'footer'),
('footer_legal_aviso', 'Aviso Legal', 'Legal Notice', 'footer'),
('footer_legal_terminos', 'Términos y Condiciones', 'Terms & Conditions', 'footer'),
('footer_legal_privacidad', 'Privacidad', 'Privacy Policy', 'footer'),
('footer_legal_cookies', 'Cookies', 'Cookies Policy', 'footer'),
('footer_cards', 'Aceptamos tarjetas', 'We accept cards', 'footer'),
('footer_copyright', '© 2026 Bar Luna Llena 16. Todos los derechos reservados.', '© 2026 Bar Luna Llena 16. All rights reserved.', 'footer'),
('footer_made_by', 'Made by', 'Made by', 'footer'),
('res_title', 'Haz tu Reserva', 'Book a Table', 'reservation'),
('res_people', 'Personas', 'People', 'reservation'),
('res_date', 'Día', 'Date', 'reservation'),
('res_time', 'Hora', 'Time', 'reservation'),
('res_allergies', '¿Alguna Alergia?', 'Any Allergies?', 'reservation'),
('res_allergies_placeholder', 'Ej: Sin gluten, intolerancia a la lactosa...', 'E.g. Gluten-free, lactose intolerant...', 'reservation'),
('res_submit_btn', 'Enviar por WhatsApp', 'Send via WhatsApp', 'reservation'),
('fab_step1_title', '¿Qué necesitas?', 'What do you need?', 'fab'),
('fab_step1_btn1_title', 'Reservar Mesa', 'Book a Table', 'fab'),
('fab_step1_btn1_desc', 'Elige fecha, hora y personas', 'Choose date, time and guests', 'fab'),
('fab_step1_btn2_title', 'Hacer un Pedido', 'Place an Order', 'fab'),
('fab_step1_btn2_desc', 'Te avisamos por WhatsApp', 'We will notify you via WhatsApp', 'fab'),
('fab_step2_back', 'Volver', 'Back', 'fab'),
('fab_step2_title', 'Tu Pedido', 'Your Order', 'fab'),
('fab_step2_placeholder_name', 'Nombre *', 'First Name *', 'fab'),
('fab_step2_placeholder_surname', 'Apellidos', 'Last Name', 'fab'),
('fab_step2_placeholder_phone', 'Teléfono *', 'Phone Number *', 'fab'),
('fab_step2_checkbox_title', '¿Qué te apetece?', 'What do you fancy?', 'fab'),
('fab_step2_cat_tapas', 'Tapas', 'Tapas', 'fab'),
('fab_step2_cat_burgers', 'Burgers', 'Burgers', 'fab'),
('fab_step2_cat_portions', 'Raciones', 'Portions', 'fab'),
('fab_step2_cat_drinks', 'Bebidas', 'Drinks', 'fab'),
('fab_step2_placeholder_notes', 'Detalles del pedido...', 'Order details...', 'fab'),
('fab_step2_submit', 'Enviar por WhatsApp', 'Send via WhatsApp', 'fab'),
('cookies_title', 'Tu privacidad es importante', 'Your privacy matters', 'cookies'),
('cookies_desc', 'Utilizamos cookies para mejorar tu experiencia, analizar el tráfico y personalizar el contenido.', 'We use cookies to improve your experience, analyze traffic and personalize content.', 'cookies'),
('cookies_link', 'Política de Privacidad', 'Privacy Policy', 'cookies'),
('cookies_btn_options', 'Más Opciones', 'More Options', 'cookies'),
('cookies_btn_accept', 'Aceptar', 'Accept', 'cookies')
ON CONFLICT (key) DO UPDATE SET 
    value_es = EXCLUDED.value_es,
    value_en = EXCLUDED.value_en,
    category = EXCLUDED.category;

-- Platos Destacados
INSERT INTO public.dishes (key, title_es, title_en, description_es, description_en, image_url) VALUES
('burger', 'Burger Luna Llena', 'Luna Llena Burger', 'Jugosa carne doble seleccionada 100% vacuno con queso fundido, lechuga y tomate en pan artesanal. Acompañada de patatas fritas.', 'Juicy double premium 100% beef patty with melted cheese, lettuce and tomato in artisan bread. Served with french fries.', './assets/burger.jpg'),
('bravas', 'Bravas Caseras', 'Homemade Bravas', 'Auténticas patatas cortadas a mano, fritas al momento y bañadas en nuestra salsa brava casera secreta con un toque suave de alioli premium.', 'Authentic hand-cut potatoes, freshly fried and topped with our secret homemade brava sauce with a smooth touch of premium aioli.', './assets/tapas.jpg'),
('pepito', 'Pepito Clásico', 'Classic Pepito', 'Lomo tierno a la plancha con pimientos asados seleccionados y queso fundido, servido en pan rústico crujiente recién horneado. El clásico de siempre.', 'Tender grilled pork loin with roasted peppers and melted cheese, served in crispy freshly baked rustic bread. A timeless classic.', './assets/pepito.jpg')
ON CONFLICT (key) DO UPDATE SET 
    title_es = EXCLUDED.title_es,
    title_en = EXCLUDED.title_en,
    description_es = EXCLUDED.description_es,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
